id: I523112F4
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T17:20:23.561707'
last_modified: '2022-05-27T17:20:23.561721'
parser: null
source_metadata:
  title: 'MSV 1,08: Kaṭhinavastu'
  language: bo
  base:
    fF866:
      title: Kaṭhinavastu
      base_file: fF866.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
